### ISSUE TITLE
PRE-RELEASE CHECKLIST

### ISSUE THREAD

**Issue by gtfargo** [Scandy-co/cappy-web#12]
- [ ] Supported Browsers tested (safari, firefox, chrome, "oh-pear-uh")
- [ ] DNS prepped and TTLs 1 min
- [ ] SEO
  - [ ] Title Tags
  - [ ] Meta Tags (social, browser, etc, all defined)
  - [ ] Sitemap (XML for google)
  - [ ]  Sitemap (“human readable”)
- [ ] Error Pages  
  - [ ] 404,500,503, etc
- [ ] Validation
  - [ ] HTML
  - [ ] CSS
  - [ ] JS
- [ ] Compression
  - [ ] Image 
  - [ ] html/js/css 
  - [ ] CDN for all static assets
- [ ] SSL
- [ ] Favicon / apple touch icons
- [ ] Action indicators on every action button - pre, process, post. 
- [ ] Error messages
- [ ] Success Messages
- [ ] Analytics
- [ ] Google webmaster tools
- [ ] Google lighthouse for progressive web apps
- [ ] Google page speed insights
- [ ] [A11y accessibility checks](https://addyosmani.com/a11y/)
- [ ] Marketing automation system installed and set up (drip, mailchimp, sumome, etc)
- [ ] Intercom installed and setup
- [ ] All test data is scrubbed
- [ ] All env variables are set for production
- [ ] Sharing with sumome or whatever works
- [ ] Privacy Policy
- [ ] Terms and Conditions
- [ ] Copyright
